### ISSUE TITLE
Need help in android 7 with proxy

### ISSUE THREAD

**Issue by sunnysachdeva** [levyitay/AddSecurityExceptionAndroid#11]
HI ,

We are using appium library with BMP (https://github.com/lightbody/browsermob-proxy) to capture requests from native android app. Till version 6, it was fine but from android 7 onwards, the existing solution did not worked, perhaps due to google security restriction.

I tried ur script but still not able to intercept traffic... 

Pls let me know if you can give some pointers.

Thanks

**Comment by vikasprasadste** [comment]
I am trying to edit the network_security_config.xml to add some schema but its not building myapk_new.apk, which jarsigner looks to sign the .apk file

I am running this command : ./addSecurityExceptions.sh /Users/admin/Desktop/myapk.apk ~/.android/debug.keystore

actual network_security_config.xml:

`<?xml version="1.0" encoding="utf-8"?>
<network-security-config ”>
    <base-config>
        <trust-anchors>
            <certificates src="system" />
			<certificates src="user" />
        </trust-anchors>
    </base-config>
    <debug-overrides>
        <trust-anchors>
            <certificates src="user" />
        </trust-anchors>
    </debug-overrides>
</network-security-config> `


expected .xml:

`<?xml version="1.0" encoding="utf-8"?>
<network-security-config xmlns:android=“http://schemas.android.com/apk/res/android”>
    <base-config>
        <trust-anchors>
<certificates src=“@raw/custom_ca” />
            <certificates src="system" />
			<certificates src="user" />
        </trust-anchors>
    </base-config>
    <debug-overrides>
        <trust-anchors>
            <certificates src="user" />
        </trust-anchors>
    </debug-overrides>
</network-security-config>`


error:
jarsigner: unable to open jar file: ./myapk_new.apk

**Comment by levyitay** [comment]
probably something in the re-build phase of the apk didn't work correctly. 
Do you still have that issue?

**Comment by levyitay** [comment]
Do you still need help here? 
Did you manage to fix it?

**Comment by sunnysachdeva** [comment]
@levyitay this is fixed hence closing this
