### ISSUE TITLE
Fails when apk file name contains spaces

### ISSUE THREAD

**Issue by markstos** [levyitay/AddSecurityExceptionAndroid#13]
It seems required to quote the variables in `bash` that contain a path which may contain spaces.

**Comment by markstos** [comment]
I tried patching the batch myself, but Java seemed to have a problems with the spaces too. 

Renaming the APK to not contain spaces was the easier workaround!

**Comment by levyitay** [comment]
Yeah might need to use escape chars

**Comment by markstos** [comment]
Why was this closed when the issue was not fixed?

**Comment by levyitay** [comment]
@markstos not sure this can be fixed really since it might be a JAVA issue.. 
I might do some wired workaround by moving the APK first to temp folder without spaces and run the process on it.

**Comment by markstos** [comment]
I agree it might be a Java issue. I know Bash fairly well and I thought I had tested a fixing the bash part of it locally.  I'm less familiar with what escaping Java might require.

A simple resolution could be adding a disclaimer to the README to mention that APKs with spaces or other special characters are not supported and should be renamed first.
