### ISSUE TITLE
Still not working even with AddSecurityException

### ISSUE THREAD

**Issue by programmin1** [levyitay/AddSecurityExceptionAndroid#18]
I am on Ubuntu 16.04.6 LTS and I can create a exception version of an app, I am still getting an error with mitmproxy. adb logcat shows:

06-02 00:01:48.191 24113 25761 E AndroidCll-EventQueueWriter: Cannot send event: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

I am however getting https from others. Can I detect if this is cert pinning?

**Comment by levyitay** [comment]
Looks like the server is validating the SSL certificate and denies it. 
So basically some servers are validating the ssl certificate (Google and FB are doing it for some of their services) and using man in the middle certificate won't work. 
Has nothing todo with the script.
