### ISSUE TITLE
AndroidManifest.xml:26: error: No resource identifier found for attribute 'isSplitRequired' in package 'android'

### ISSUE THREAD

**Issue by kwhat** [levyitay/AddSecurityExceptionAndroid#20]
This tool somehow requires apktool 2.4.1 which has not been released yet.

**Comment by levyitay** [comment]
The tool doesn't require 2.4.1 but your apk is built with newer api. 
you can manually download apktool 2.4.1 and replace it with the jar in the build

**Comment by DavidBalas1** [comment]
I compilede apktool v2.4.1 from this commit (https://github.com/iBotPeaches/Apktool/commit/c2065995ed5d4e1b69b701c27a0f02f49e528d7b) -- you can use this jar and the issue will be solved :)

[apktool.zip](https://github.com/levyitay/AddSecurityExceptionAndroid/files/3708901/apktool.zip)

איתי, נראה לי שאתה יכול לסגור את הבעיה הזאתי

**Comment by levyitay** [comment]
closing this one

**Comment by kwhat** [comment]
@DavidBalas1 thanks for the pre-compiled binary.

@levyitay no binary is available for 2.4.1 yet.
