### ISSUE TITLE
Analysis Error

### ISSUE THREAD

**Issue by ravillarreal** [levyitay/AddSecurityExceptionAndroid#22]
When i try to install the modified apk it throws me that error.

Steps to reproduce:
1.- Clone the repository
2.- Copy the apk file inside the repository's folder
3.- Open a Powershell terminal and execute ".\addSecurityExceptions.sh .\app_name.apk"
4.- Copy the app_name_new.apk to the phone and tap to install.

**Comment by levyitay** [comment]
@ravillarreal This script was not intended for Powershell
Also it will be useful to share the error...

**Comment by levyitay** [comment]
Closing
