### ISSUE TITLE
Runing the script in wsl (Windows Subsystem for Linux)

### ISSUE THREAD

**Issue by shraga100** [levyitay/AddSecurityExceptionAndroid#24]
I'm running the script, (I'm using wsl in windows 10)
And an error appears:
./addSecurityExceptions.sh: line 49: jarsigner: command not found

what can be done?
Is it a script bug or a problem on my computer?
![2020-01-30](https://user-images.githubusercontent.com/26792728/73472765-3adcef80-4394-11ea-9522-472242f63f68.png)

**Comment by levyitay** [comment]
The script was not intended to run on Windows. 
It looks like you are missing jarsigner executable probably missing JDK

**Comment by shraga100** [comment]
תודה,
ידוע לך כיצד להתקין את jarsigner  בwindows?
(אם מתחשק לך לעשות פרוטקציה לישראלי...)

**Comment by levyitay** [comment]
Sorry,
I'm on mac and didn't spend much time on windows / powershell

**Comment by shraga100** [comment]
I'm just updating the solution,
Need to run first this command:
`sudo apt-get update`
And then
`sudo apt install default-jdk`

Another option (which I came up with before reaching the right solution):
Replace line 49 with this line:
`java -jar "$ DIR / uber-apk-signer-1.1.0.jar" --apks "./$newFileName"`

(Don't forget to put the uber-apk-signer-1.1.0.jar file in the script folder 
[You can download this from here](https://github.com/patrickfav/uber-apk-signer/releases/download/v1.1.0/uber-apk-signer-1.1.0.jar)

**Comment by shraga100** [comment]
Another option (which I came up with before reaching the right solution):
Replace line 49 with this line:
java -jar "$ DIR / uber-apk-signer-1.1.0.jar" --apks "./$newFileName"

(Don't forget to put the file in the script folder the uber-apk-signer-1.1.0.jar file
[You can download from here](https://github.com/patrickfav/uber-apk-signer/releases/download/v1.1.0/uber-apk-signer-1.1.0.jar)
