### ISSUE TITLE
You should add this

### ISSUE THREAD

**Issue by mortenmoulder** [levyitay/AddSecurityExceptionAndroid#3]
I don't have time to make a pull request, but you should add this to the description:

- Keystore password should be **android**
- Keystore alias should be **androiddebugkey**

Other than that, I had no issues getting this to work. The APK I got, had malformed XML in it, which meant apktool could not generate the APK file. Seems like there is no way to ignore that, so I had to go fix the XML errors myself, then run the apktool and jarsigner commands individually.

Thanks

**Comment by TylerRick** [comment]
My system didn't have any keystore, so based on your comment here and instructions I found [elsewhere](https://stackoverflow.com/questions/4282405/keytool-and-jarsigner-tool), I finally figured out that I need to run this command to generate a keystore file:
```
keytool -genkey -alias androiddebugkey -keypass android -keystore ~/.android/debug.keystore
```
I hope this helps someone else... and gets added to the docs :)

**Comment by levyitay** [comment]
Thanks guys, 
Fixed the script.
