### ISSUE TITLE
Can you tell me the dependencies and version requirements, please?

### ISSUE THREAD

**Issue by Huansheng1** [levyitay/AddSecurityExceptionAndroid#40]
Hello, excuse me, I have some problems with this script, I would like to ask if this tool can be used in window or must be used in linux, and what dependencies  it depends on, I only saw `java` in the readme, I tried to test it directly in window, but it reported an error, of course I haven't installed java, just want to I just want to see what dependencies are needed, it looks like more than java?
![image](https://github.com/levyitay/AddSecurityExceptionAndroid/assets/33859558/1dc486bd-54d9-45b1-85b0-1db3ce428760)

eg:Android 、keytools？Can you tell me the dependencies and version requirements, please?

One last question, does it work for flutter apps.

**Comment by levyitay** [comment]
Hi, 
It will only work on Mac / Linux

**Comment by Huansheng1** [comment]
> Hi, It will only work on Mac / Linux

Thank you for your reply, can you tell me what else I need to install on the mac besides java;
And will it work for flutter apps?

**Comment by levyitay** [comment]
Never tried on flutter apps but it should work.
you should also have android sdk installed

**Comment by Huansheng1** [comment]
> Never tried on flutter apps but it should work. you should also have android sdk installed

Thank you very much!
