### ISSUE TITLE
Cannot build apk

### ISSUE THREAD

**Issue by bogomazov** [levyitay/AddSecurityExceptionAndroid#5]
I am using the defualt keystore option.

As an apk file. Facebook's Messenger app.
Here is what I get.

> W: /tmp/com.facebook.orca_v131.0.0.17.89-68164425_Android-4.0.3/res/values/plurals.xml:312: error: Multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?
> W: 
> W: /tmp/com.facebook.orca_v131.0.0.17.89-68164425_Android-4.0.3/res/values/plurals.xml:312: error: Found tag </item> where </plurals> is expected
> W: 
> Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/ky/r906534s3svbw0l_9m3_mgfm0000gn/T/brut_util_Jar_4762472172826358745.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 23, --version-code, 68164425, --version-name, 131.0.0.17.89, --no-version-vectors, -F, /var/folders/ky/r906534s3svbw0l_9m3_mgfm0000gn/T/APKTOOL534443114401297775.tmp, -0, arsc, -0, assets/InboxV2Query_MessengerInboxUnits_Nodes.fbs.md5, -0, assets/MessengerBundle.js.meta, -0, txt, -0, assets/java.com.facebook.messaging.particles.downloadableparticles/java.com.facebook.messaging.particles.downloadableparticles-1.dex.jar.xzs.tmp~.meta, -0, assets/java.com.facebook.messaging.particles.downloadableparticles/java.com.facebook.messaging.particles.downloadableparticles.dex.jar.xzs, -0, xzs, -0, assets/secondary-program-dex-jars/secondary.dex.jar.xzs, -0, json, -0, bks, -0, arsc, -I, /Users/andrey/Library/apktool/framework/1.apk, -S, /tmp/com.facebook.orca_v131.0.0.17.89-68164425_Android-4.0.3/res, -M, /tmp/com.facebook.orca_v131.0.0.17.89-68164425_Android-4.0.3/AndroidManifest.xml]

**Comment by levyitay** [comment]
I Just updated the script and tested Facebook's Messenger apk I found online.
Should work now.

**Comment by abhishekjebaraj** [comment]
The solution here https://github.com/iBotPeaches/Apktool/issues/1376#issuecomment-400357321 worked. I had to edit the shell file and added the '-r' parameter.
